[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Set IO permissions for the scripts
fs_permissions = [{ access = "read-write", path = "C:/"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
local = "${NODE_RPC_URL}"
